#!/bin/bash
#
# Copyright (C) 2007 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Set up prog to be the path of this script, including following symlinks,
# and set up progdir to be the fully-qualified pathname of its directory.
prog="$0"
while [ -h "${prog}" ]; do
    newProg=`/bin/ls -ld "${prog}"`
    newProg=`expr "${newProg}" : ".* -> \(.*\)$"`
    if expr "x${newProg}" : 'x/' >/dev/null; then
        prog="${newProg}"
    else
        progdir=`dirname "${prog}"`
        prog="${progdir}/${newProg}"
    fi
done
progdir=`dirname "${prog}"`
cd "${progdir}"
progdir=`pwd`

# Be in the parent of the progdir when running the rest of the script.
cd ".."

${progdir}/opcode-gen dx/src/com/android/dx/dex/code/Dops.java
${progdir}/opcode-gen dx/src/com/android/dx/dex/code/RopToDop.java
${progdir}/opcode-gen dx/src/com/android/dx/io/OpcodeInfo.java
${progdir}/opcode-gen dx/src/com/android/dx/io/Opcodes.java
${progdir}/opcode-gen libdex/DexOpcodes.cpp
${progdir}/opcode-gen libdex/DexOpcodes.h
${progdir}/opcode-gen libdex/InstrUtils.cpp

# It's a minor shame that these files live in a different top-level project.
# So it goes.
${progdir}/opcode-gen \
    ../libcore/dalvik/src/main/java/dalvik/bytecode/OpcodeInfo.java
${progdir}/opcode-gen \
    ../libcore/dalvik/src/main/java/dalvik/bytecode/Opcodes.java
