#!/bin/sh

find ../src -name \*java | xargs javac -d build -Xlint:unchecked

# debug launch line tha turns off the jit and runs a debug server
#java -Djava.compiler=NONE -Xdebug -Xrunjdwp:transport=dt_socket,address=53635,server=y,suspend=y -cp build com.android.hit.Main ../samples/android.hprof

java -cp build com.android.hit.Main ../samples/android.hprof
